      SUBROUTINE AERTMP

!     THIS ROUTINE DETERMINES AEROSOL DENSITY
!     WEIGHTED PATH AVERAGED TEMPERATURES

!     PARAMETERS:
      INCLUDE 'PARAMS.h'

!     COMMONS:
      INCLUDE 'BASE.h'

!     /CNTRL/
!       IKMAX    NUMBER OF PATH SEGMENTS ALONG LINE-OF-SIGHT.
!       ML       NUMBER OF ATMOSPHERIC PROFILE LEVELS.
!       MLFLX    NUMBER OF LEVELS FOR WHICH FLUX VALUES ARE WRITTEN.
!       ISSGEO   LINE-OF-SIGHT FLAG (0 = SENSOR PATH, 1 = SOLAR PATHS).
!       IMULT    MULTIPLE SCATTERING FLAG
!                  (0=NONE, 1=AT SENSOR, -1=AT FINAL OR TANGENT POINT).
      INTEGER IKMAX,ML,MLFLX,ISSGEO,IMULT
      COMMON/CNTRL/IKMAX,ML,MLFLX,ISSGEO,IMULT
      REAL TAER
      COMMON/AERTM/TAER(MAER)

!     DECLARE LOCAL VARIABLES
      INTEGER IAER,M,IK

!     LIST DATA
      INTEGER MAP(MAER)
      DATA MAP/7,12,13,14,16,66,67,68,69,70,71,72,73,74,75,76,77/
      DO 20 IAER=1,MAER
          M=MAP(IAER)
          TAER(IAER)=TBBY(1)
          IF(W(M).LE.0)GOTO20
          TAER(IAER)=TBBY(1)*WPATH(1,M)
          DO 10 IK=2,IKMAX
              TAER(IAER)=TAER(IAER)+TBBY(IK)*WPATH(IK,M)
   10     CONTINUE
          TAER(IAER)=TAER(IAER)/W(M)
   20 CONTINUE
      RETURN
      END
