
!     /BASE/
!       KPOINT   ARRAY MAPPING MOLECULAR SPECIES (MOLSPC) TO THEIR
!                LOCATION IN THE COLUMN AMOUNT ARRAY (WPATH).
!       WAVLEN   AEROSOL OPTICAL PROPERTIES WAVELENGTH GRID [MICRONS].
!       DRNG     PATH LENGTH THROUGH A LAYER [KM].
!       PATM     DENSITY-WEIGHTED LAYER PRESSURE [ATM].
!       TBBY     DENSITY-WEIGHTED LAYER TEMPERATURE [K].
!       WPATH    INCREMENTAL MOLECULAR COLUMN AMOUNTS
!                FOR BAND MODEL SPECIES [ATM CM].
      INTEGER KPOINT
      REAL AWCCON,WAVLEN,EXTC,ABSC,ASYM,TX,W,RELHUM,DRNG,PATM,TBBY,WPATH
      COMMON/BASE/KPOINT(NMOLXT),AWCCON(MAER),WAVLEN(MXWVLN),           &
     &  EXTC(MAER,MXWVLN),ABSC(MAER,MXWVLN),ASYM(MAER,MXWVLN),          &
     &  TX(MEXTX),W(MEXT),RELHUM(LAYDIM),DRNG(LAYTHR),                  &
     &  PATM(LAYTHR),TBBY(LAYTHR),WPATH(LAYTHR,MEXTX)
