
!     /IFIL/ FILE UNIT NUMBERS (DEFINED IN devcbd.f)
!       NPR      PRINTOUT LEVEL SWITCH (1=SMALL,0=NORMAL,-1=LARGE).
!       IRD      01 PRIMARY INPUT FILE:
!                   tape5 or <ROOTNAME>.tp5, ASCII.
!       IPR      02 PRIMARY OUTPUT FILE:
!                   tape6 or <ROOTNAME>.tp6, ASCII.
!       IPU      07 SPECTRAL DATA FILE:
!                   tape7 or <ROOTNAME>.tp7, ASCII.
!       IPR1     08 LINE-OF-SIGHT MULTIPLE SCATTERING FILE:
!                   tape8 or <ROOTNAME>.tp8, ASCII.
!       ITB      09 MOLECULAR BAND MODEL DATA:
!                   'DATA/B2001_01.BIN' or BMNAME input, BINARY.
!       ITBX     11 MOLECULAR (CFC) ABSORPTION COEFFICIENT DATA.
!                   'DATA/CFC99_01.ASC' or 'DATA/CFC99_15.ASC', ASCII.
!       ISCRCH   12 MULTIPLE SCATTERING DATA SAVED FOR REPEAT RUNS:
!                   SCRATCH FILE, BINARY.
!       IPLOT    13 SPECTRAL TRANSMITTANCE, RADIANCE OR IRRADIANCE FILE:
!                   pltout or <ROOTNAME>.plt, ASCII.
!       IPUSCR   14 SPECTRAL DATA SAVED FOR REPEAT RUNS:
!                   tape7.scr or <ROOTNAME>.7sr, ASCII.
!       IPUSCN   15 SPECTRALLY DEGRADED (SCANNED) tape7 FILE:
!                   tape7.scn or <ROOTNAME>.7sc, ASCII.
!       IPTSCN   16 SPECTRALLY DEGRADED (SCANNED) pltout FILE:
!                   pltout.scn or <ROOTNAME>.psc, ASCII.
!       IFLUX    17 SPECTRAL FLUX FILE:
!                   specflux or <ROOTNAME>.flx, ASCII.
!       ICR      18 SPECTRAL COOLING RATE FILE:
!                   clrates or <ROOTNAME>.clr, ASCII.
!       IDBIN    19 DATABASE INPUT FILE: <ROOTNAME>.dbi, ASCII.
!       IDBOUT   20 DATABASE OUTPUT FILE: <ROOTNAME>.dbo, ASCII.
!       I3DGEN   21 OUTPUT FILE OF GENERAL INFORMATION FOR MOD3D.
!       I3DCNT   22 OUTPUT FILE OF CONTINUA DATA FOR MOD3D.
!       I3DDAT   23 OUTPUT FILE OF MOLECULAR EXTINCTION BY ATMOSPHERE.
!       I3DMOL   24 OUTPUT FILE OF MOLECULAR EXTINCTION DATA FOR MOD3D.
      INTEGER NPR,IRD,IPR,IPU,IPR1,ITB,ITBX,ISCRCH,                     &
     &  IPUSCR,IPUSCN,IFLUX,ICR,                                        &
     &  IDBIN,IDBOUT,I3DGEN,I3DCNT,I3DDAT,I3DMOL
      REAL IPLOT(5000,2)
      REAL IPTSCN(1000,2) 
      COMMON/IFIL/NPR,IRD,IPR,IPU,IPR1,ITB,ITBX,ISCRCH,                 &
     &  IPLOT,IPUSCR,IPUSCN,IPTSCN,IFLUX,ICR,                           &
     &  IDBIN,IDBOUT,I3DGEN,I3DCNT,I3DDAT,I3DMOL
      SAVE/IFIL/
