
!     /BMDAT/
!       SD       ABSORPTION COEFFICIENT MOLECULAR BAND MODEL PARAMETERS
!                FOR THE CURRENT SPECTRAL FREQUENCY BIN [ATM-1 CM-1].
!       OD       LINE SPACING MOLECULAR BAND MODEL PARAMETERS FOR THE
!                CURRENT SPECTRAL FREQUENCY BIN [CM].
!       ALF0     THE STP LORENTZ/COLLISION LINE WIDTH PARAMETERS FOR
!                THE CURRENT SPECTRAL FREQUENCY BIN [CM-1].
!       T5       SQUARE ROOT OF THE LAYER TO STANDARD TEMPERATURE
!                RATIO, I.E. T[K] / 273.15K.
!       JJ       UPPER TEMPERATURE INTERPOLATION INDEX FOR BAND MODEL
!                PARAMETERS.
!       FF       TEMPERATURE INTERPOLATION FRACTION USED WITH JJ.
!       T5S      SQUARE ROOT OF THE PATH-AVERAGE TO STANDARD TEMPERATURE
!                RATIO (I.E. T[K] / 273.15K) FOR EACH MOLECULAR SPECIES.
!       JJS      UPPER TEMPERATURE INTERPOLATION INDEX FOR BAND MODEL
!                PARAMETERS BASED ON THE PATH-AVERAGED TEMPERATURE.
!       FFS      TEMPERATURE INTERPOLATION FRACTION USED WITH JJS.
!       DOP0     THE STP DOPPLER LINE WIDTH PARAMETERS FOR THE CURRENT
!                SPECTRAL FREQUENCY BIN [CM-1].
      INTEGER JJ,IBIN,IP,IMOL,IALF,JJS
      REAL SDZ,ODZ,T5,PTM75,FF,T5S,PTM75S,FFS,DOP0,SD,OD,ALF0
      COMMON/BMDAT/SDZ(MXTEMP),ODZ(MXTEMP),T5(LAYTHR),PTM75(LAYTHR),    &
     &  JJ(LAYTHR),FF(LAYTHR),T5S(LAYTHR,NMOL),PTM75S(LAYTHR,NMOL),IBIN,&
     &  IP,IMOL,IALF,JJS(LAYTHR,NMOLXT),FFS(LAYTHR,NMOLXT),DOP0(NMOLXT),&
     &  SD(1:MXTEMP,1:NMOLXT,0:MTLSUB),OD(MXTEMP,NMOLXT),ALF0(NMOLXT)
      SAVE /BMDAT/
