      SUBROUTINE BMXLD

!     THIS ROUTINE IS THE EQUIVALENT OF BMLOAD FOR THE X-MOLECULES.

!     THIS SUBROUTINE (CALLED BY BMOD) LOADS BAND MODEL DATA FOR A SINGL
!     PARAMETER SET INTO THE MATRICES SDX, ODX AND ALF0X (FOUND IN /BMDC

      INCLUDE 'PARAMS.h'

!     TRANS VARIABLES
      INTEGER IBINX,IMOLX,IALFX
      REAL SDZX,ODZX
      COMMON/BMDCMX/SDZX(MXTEMP),ODZX(MXTEMP),IBINX,IMOLX,IALFX
      INCLUDE 'BMHEAD.h'
      INCLUDE 'BMDAT.h'

!     LOCAL VARIABLES:
      INTEGER IMX,JMX,IT

!     FILL THE SDX, ODX AND ALF0X MATRICES:
      IF(IMOLX.LE.NMOLX)THEN

!         LINE CENTER CONTRIBUTIONS:
          IMX=IMOLX+NMOL
          DO 10 IT=1,NTEMP
              SD(IT,IMX,0)=SDZX(IT)
              OD(IT,IMX  )=ODZX(IT)
              SD(IT,IMX,1)=0.
   10     CONTINUE
          ALF0(IMX)=1.E-04*IALFX
      ELSE

!         LINE TAIL CONTRIBUTIONS:
          IMX=IMOLX-NMOLX+NMOL
          IF(IALFX.EQ.0)THEN

!             ONE TAIL:
              DO 20 IT=1,NTEMP
                  SD(IT,IMX,1)=SDZX(IT)
   20         CONTINUE
          ELSE

!             TWO TAILS:
              JMX=IALFX-NMOLX+NMOL
              DO 30 IT=1,NTEMP
                  SD(IT,IMX,1)=SDZX(IT)
                  SD(IT,JMX,1)=ODZX(IT)
   30         CONTINUE
          ENDIF
      ENDIF
      RETURN
      END
