      REAL FUNCTION C4DTA(IV)

!     RETURN N2 CONTINUUM ABSORPTION COEFFICIENT.

!     INPUT ARGUMENTS:
!       IV      FREQUENCY [CM-1].

!     COMMONS:

!     /C4DAT/
!       C4      ABSORPTION COEFFICIENTS.
      REAL C4
      COMMON/C4DAT/C4(133)

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      SAVE /C4DAT/
      EXTERNAL C4D
      IF(IV.LT.2080 .OR. IV.GT.2740)THEN
          C4DTA=0.
      ELSE
          C4DTA=C4((IV-2075)/5)
      ENDIF
      RETURN
      END
