
!     PARAMETERS:
!       MXCHAN   MAXIMUM NUMBER OF CHANNELS READ FROM FILTER
!                FUNCTION FILE.
!       MNBIN    MINIMUM SPECTRAL BIN USED IN CHANNEL INTEGRATIONS
!                (CORRESPONDS TO FREQUENCY MNBIN*IBNDWD cm-1).
!       MXBIN    MAXIMUM SPECTRAL BIN USED IN CHANNEL INTEGRATIONS
!                (CORRESPONDS TO FREQUENCY MXBIN*IBNDWD cm-1).
!       MXNCHN   MAXIMUM NUMBER OF CHANNELS FOR ANY SPECTRAL BIN.
      INTEGER MXCHAN,MNBIN,MXBIN,MXNCHN
!sav  PARAMETER(MXCHAN=400,MNBIN=0/15,MXBIN=205,MXNCHN=10)
!sav  PARAMETER(MXCHAN=400,MNBIN=3900/15,MXBIN=28005,MXNCHN=10)
      PARAMETER(MXCHAN=400,MNBIN=765/15,MXBIN=28005,MXNCHN=10)

!     CHANNEL SPECTRAL RESPONSE COMMONS:
!       ICHNUN   UNIT NUMBER FOR FILTER RESPONSE FUNCTION OUTPUT FILE.
!       CHNOUT   FILTER RESPONSE FUNCTION OUTPUT FILE NAME.
!       LENCHN   LENGTH OF FILTER RESPONSE FUNCTION OUTPUT FILE NAME.
!       NCHAN    TOTAL NUMBER OF BAND PASS CHANNELS.
!       UNTFLG   SPECTRAL GRID UNIT FLAG ['W' for Wavenumbers,
!                'M' for Microns, and 'N' for Nanometers].
!       VLCHAN   VALUE OF INTEGRATION OVER CHANNEL
!                  (IN-BAND RADIANCE [W SR-1 CM-2] IF IEMSCT=1 OR =2,
!                  IN-BAND EXTINCTION IF IEMSCT=0, AND TRANSMITTED
!                  SOLAR IRRADIANCE [W CM-2] IF IEMSCT=3).
!       NMCHAN   CHANNEL NAME (MAXIMUM OF 80 CHARACTERS).
!       LNCHAN   LENGTH OF CHANNEL NAME.
!       WDFREQ   INTEGRATED WIDTH OF CHANNEL [CM-1].
!       WDWAVE   INTEGRATED WIDTH OF CHANNEL
!                  [NANOMETERS IF UNTFLG='N', OTHERWISE MICRONS].
!       SPECLO   MINIMUM CHANNEL SPECTRAL POINT [MICRONS IF UNTFLG='M',
!                  NANOMETERS IF UNTFLG='N', OTHERWISE WAVENUMBERS].
!       SPECHI   MAXIMUM CHANNEL SPECTRAL POINT [MICRONS IF UNTFLG='M',
!                  NANOMETERS IF UNTFLG='N', OTHERWISE WAVENUMBERS].
!       NFRQLO   FREQUENCY OF MINIMUM CALCULATIONAL SPECTRAL BIN [CM-1].
!       NFRQHI   FREQUENCY OF MAXIMUM CALCULATIONAL SPECTRAL BIN [CM-1].
!       NUMCHN   NUMBER OF CHANNELS FOR EACH SPECTRAL BIN.
!       LSTCHN   LIST OF CHANNEL NUMBERS FOR EACH SPECTRAL BIN.
!       WTCHN    LIST OF WEIGHTS FOR EACH SPECTRAL BIN.
      INTEGER ICHNUN,LENCHN,NCHAN,LNCHAN,NFRQLO,NFRQHI,NUMCHN,LSTCHN
      REAL VLCHAN,WDFREQ,WDWAVE,SPECLO,SPECHI,WTCHN
      COMMON/CHANEL/ICHNUN,LENCHN,NCHAN,VLCHAN(MXCHAN),LNCHAN(MXCHAN),
     1  WDFREQ(MXCHAN),WDWAVE(MXCHAN),SPECLO(MXCHAN),SPECHI(MXCHAN),
     2  NFRQLO(MXCHAN),NFRQHI(MXCHAN),NUMCHN(MNBIN:MXBIN),
     3  LSTCHN(1:MXNCHN,MNBIN:MXBIN),WTCHN(1:MXNCHN,MNBIN:MXBIN)
      CHARACTER UNTFLG*1,CHNOUT*100,NMCHAN*80
      COMMON/CCHANL/UNTFLG,CHNOUT,NMCHAN(MXCHAN)
