      SUBROUTINE DPSCHT(Z1,Z2,RFNDX1,RFNDX2,SH,GAMMA)

!     THE DOUBLE PRECISION VERSION OF THE PREVIOUS ROUTINE SCALHT.
!     THIS SUBROUTINE CALCULATES THE SCALE HEIGHT SH OF THE
!     (INDEX OF REFRACTION-1) FROM THE VALUES OF THE INDEX AT
!     THE ALTITUDES Z1 AND Z2 ( Z1 < Z2).  IT ALSO CALCULATES
!     THE EXTRAPOLATED VALUE GAMMA OF THE (INDEX-1) AT Z = 0.

!     DECLARE ROUTINE ARGUMENTS:
      DOUBLE PRECISION Z1,Z2,RFNDX1,RFNDX2,SH,GAMMA

!     DECLARE LOCAL VARIABLES:
      DOUBLE PRECISION RATIO,ZDIFF
      SH=0.D0
      GAMMA=RFNDX1
      RATIO=(RFNDX1+1.D-20)/(RFNDX2+1.D-20)
      IF(ABS(RATIO-1.D0).LT.1.D-5)RETURN

!     ACCOUNT FOR CHANGE IN INDEX OF REFRACTION ACROSS LAYER.
      ZDIFF=Z2-Z1
      SH=ZDIFF/LOG(RATIO)
      GAMMA=GAMMA*EXP(Z1/SH)
      RETURN
      END
