      SUBROUTINE FILTSM(IVXBIN,FLTVAL)

!     THIS ROUTINE PERFORMS THE FILTER RESPONSE SUMS FOR EACH CHANNEL.

!     DECLARE ARGUMENTS:
!       IVXBIN   THE SPECTRAL BIN NUMBER [FREQUENCY = IVXBIN * IBNDWD].
!       FLTVAL   VALUE BEING SUMMED
!                  [SPECTRAL ABSORBANCE FOR IEMSCT=0 CALCULATIONS;
!                  SPECTRAL TRANSMITTED SOLAR IRRADIANCE (W CM-2 / CM-1)
!                  FOR IEMSCT=3 CALCULATIONS; OTHERWISE SPECTRAL
!                  RADIANCE (W SR-1 CM-2 / CM-1).]
      INTEGER IVXBIN
      REAL FLTVAL

!     PARAMETERS:
      INCLUDE 'CHANLS.h'

!     LOCAL VARIABLES:
!       ICHAN    CHANNEL INDEX
      INTEGER ICHAN,LCHN

!     RETURN IF SPECTRAL BIN IS OUT OF RANGE.
      IF(IVXBIN.LT.MNBIN .OR.IVXBIN.GT.MXBIN)RETURN

!     LOOP OVER CHANNELS COVERING CURRENT SPECTRAL BIN.
      DO 10 ICHAN=1,NUMCHN(IVXBIN)

!         INCREMENT SUM.
          LCHN=LSTCHN(ICHAN,IVXBIN)
          VLCHAN(LCHN)=VLCHAN(LCHN)+WTCHN(ICHAN,IVXBIN)*FLTVAL
   10 CONTINUE
      RETURN
      END
