      SUBROUTINE INTERP(INTYPE,X,X1,X2,F,F1,F2)

!     SUBROUTINE INTERP INTERPOLATES TO DETERMINE THE VALUE OF F
!     AT X, GIVEN F1 AT X1 AND F2 AT X2.
!     INTYPE=1 FOR LINEAR INTERPOLATION
!     INTYPE=2 FOR LOGARITHMIC INTERPOLATION
      IF(INTYPE.EQ.2 .AND. F1.GT.0. .AND. F2.GT.0.)THEN
          F=F1*(F2/F1)**((X-X1)/(X2-X1))
      ELSE
          F=F1+(X-X1)*(F2-F1)/(X2-X1)
      ENDIF
      RETURN
      END
