      SUBROUTINE M3DDB(KNTRVL,IKMAX,LNFLRT,FLRT)

!     M3DDB GENERATES THE MOD3D MOLECULAR DATA FILE BY CALLING M3DREW.

!     PARAMETERS:
      INCLUDE 'PARAMS.h'

!     INPUT ARGEMENTS:
!       KNTRVL   NUMBER OF ABSORPTION COEFFICIENT (K) SUB-INTERVALS.
!       IKMAX    NUMBER OF PATH SEGMENTS.
!       LNFLRT   LENGTH OF ROOT NAME FOR ALL I/O FILES.
!       FLRT     ROOT NAME FOR ALL I/O FILES.
      INTEGER KNTRVL,IKMAX
      INTEGER LNFLRT
      CHARACTER FLRT*(*)

!     COMMONS:
      INCLUDE 'IFIL.h'

!     /M3DSPC/
!       LASCII   ASCII FILE OUTPUT FLAG FOR MOD3D FILES.
!       NATM     COUNTER FOR NUMBER OF DIFFERENT MOLECULAR ATMOSPHERES.
!       IVXMIN   MINIMUM COMPUTATION SPECTRAL FREQUENCY [CM-1].
!       IVXMAX   MAXIMUM COMPUTATION SPECTRAL FREQUENCY [CM-1].
      LOGICAL LASCII
      INTEGER NATM,IVXMIN,IVXMAX
      COMMON/M3DSPC/LASCII,NATM,IVXMIN,IVXMAX
      INCLUDE 'BMHEAD.h'

!     /M3DNAM/
!       M3DGEN   NAME OF GENERAL INFORMATION FILE FOR MOD3D.
!       M3DCNT   NAME OF CONTINUA DATA FILE FOR MOD3D.
!       M3DDAT   NAME OF MOLECULAR EXTINCTION FILE SORTED BY ATMOSPHERE.
!       M3DMOL   NAME OF MOLECULAR EXTINCTION DATA FILE FOR MOD3D.
      CHARACTER*(NAMLEN) M3DGEN,M3DCNT,M3DDAT,M3DMOL
      COMMON/M3DNAM/M3DGEN,M3DCNT,M3DDAT,M3DMOL
      EXTERNAL DEVCBD

!     LOCAL VARIABLES:
!       NIVX     NUMBER OF SPECTRAL DATA POINTS.
      INTEGER NIVX

!     RETURN IF ASCII FORMAT IS BEING USED:
      IF(LASCII)RETURN

!     NUMBER OF SPECTRAL DATA POINTS:
      NIVX=(IVXMAX-IVXMIN)/IBNDWD+1

!     RE-WRITE MOLECULAR DATA:
      CALL M3DREW(NIVX,KNTRVL,IKMAX,NATM,I3DGEN,I3DDAT,I3DMOL,M3DMOL,i  &
     &            LNFLRT,FLRT)

!     RETURN TO DRIVER:
      RETURN
      END
