      REAL FUNCTION O3HHT1(V)

!     COMMONS:
      INTEGER NC
      REAL V1C,DVC,O3HH1X
      COMMON/O3HH1/V1C,DVC,NC,O3HH1X(2687)

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      SAVE /O3HH1/
      EXTERNAL BO3HH1

!     FUNCTIONS:
      REAL O3INT

!     INTERPOLATE TO DATA:
      O3HHT1=O3INT(V,V1C,DVC,NC,O3HH1X)
      RETURN
      END
