      REAL FUNCTION O3INT(V1C,V1,DV,NPT,CONTI)

!     INTERPOLATION FOR O3 CONTINUUM WITH LOWTRAN
      REAL CONTI(2687)
      I=INT((V1C-V1)/DV+1.00001)
      IF(I.GE.1 .AND. I.LE.NPT)THEN
          O3INT=CONTI(I)
      ELSE
          O3INT=0.
      ENDIF
      RETURN
      END
