      SUBROUTINE SCHRUN(V,CPRUN)
      REAL V,CPRUN
      COMMON/SHUR/SHN(430)

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      SAVE /SHUR/
      EXTERNAL SHUMG
      DATA V1,V2,DV,INUM /49600.,51710.,5.,425/
      CPRUN=-20.
      IF(V.LT.V1 .OR. V.GT.V2)RETURN
      IND=INT((V-V1)/DV+1.0001)
      IF(IND.GT.INUM)THEN
          PRINT*,'  IND GT INUM  V IND ',V,IND
          RETURN
      ENDIF
      CPRUN=SHN(IND)
      END
