      SUBROUTINE SOLZEN(L,IKMAX1,REE,DEG,ANGLE)

!     ROUTINE SOLZEN STORES THE COSINE OF THE SOLAR/LUNAR ZENITH
!     ANGLE DATA FOR THE MULTIPLE SCATTERING CALCULATIONS:
!       CSZEN0  COSINE OF SOLAR/LUNAR ZENITH AT THE GROUND.
!       CSZEN   LAYER AVERAGE COSINE OF SOLAR/LUNAR ZENITH FOR VERTICAL
!               PATH (USED IN CALCULATION OF BACKSCATTER FRACTION).
!       CSZENX  AVERAGE SOLAR/LUNAR COSINE ZENITH EXITING
!               (AWAY FROM EARTH) THE CURRENT LAYER.

!     DEFINE INPUTS
!       L       CURRENT LAYER BOUNDARY.
!       IKMAX1  NUMBER OF LAYER BOUNDARIES (NUMBER OF LAYERS PLUS ONE).
!       REE     EARTH RADIUS [KM]
!       DEG     NUMBER OF DEGREES IN ONE RADIAN
!       ANGLE   SOLAR ZENITH ANGLE AT BOUNDARY L [DEG]
      INTEGER L,IKMAX1
      REAL REE,DEG,ANGLE

!     LIST PARAMETERS
      INCLUDE 'PARAMS.h'

!     LIST COMMONS

!     /MODEL/
!       ZM       PROFILE BOUNDARY ALTITUDES [KM].
!       PM       PROFILE BOUNDARY PRESSURES [MBAR].
!       TM       PROFILE BOUNDARY TEMPERATURES [K].
!       RFNDX    PROFILE BOUNDARY REFRACTIVITIES.
!       DENSTY   PROFILE BOUNDARY DENSITIES [UNITS DEPEND ON SPECIES].
!       LRHSET   FLAG, TRUE IF RELATIVE HUMIDITY CANNOT BE SCALED.
      REAL ZM,PM,TM,RFNDX,DENSTY
      LOGICAL LRHSET
      COMMON/MODEL/ZM(LAYDIM),PM(LAYDIM),TM(LAYDIM),                    &
     &  RFNDX(LAYDIM),DENSTY(MEXT,LAYDIM),LRHSET(LAYDIM)

!     /MSRD/
!       CSSCAT   COSINE OF THE SCATTERING ANGLE.
!                (AT H1 IF IMULT=1; AT OR "NEAR" H2 IF IMULT=-1)
!       SLEGEN   Nth LEGENDRE POLYNOMIAL EVALUATED AT THE COSINE OF THE
!                SCATTERING ANGLE TIMES (2N+1)/4pi (N=0 TO NSTR-1).
!       CSZEN0   LAYER BOUNDARY COSINE OF SOLAR/LUNAR ZENITH.
!       CSZEN    LAYER AVERAGE COSINE OF SOLAR/LUNAR ZENITH.
!       CSZENX   AVERAGE SOLAR/LUNAR COSINE ZENITH EXITING
!                (AWAY FROM EARTH) THE CURRENT LAYER.
!       BBGRND   THERMAL EMISSION (FLUX) AT THE GROUND [W CM-2 / CM-1].
!       BBNDRY   LAYER BOUNDARY THERMAL EMISSION (FLUX) [W CM-2 / CM-1].
!       TCONT    LAYER CONTINUUM OPTICAL DEPTH.
!       TAUT     LAYER TOTAL OPTICAL DEPTH.
!       GTSCAT   SUM OVER SCATTERING SOURCES OF SCATTERING OPTICAL DEPTH
!                AND PHASE FUNCTION LEGENDRE COEFFICIENT PRODUCTS.
!       COSBAR   LAYER EFFECTIVE SCATTERING ASYMMETRY FACTOR.
!       DEPRAT   FRACTIONAL DECREASE IN WEAK-LINE OPTICAL DEPTH TO SUN.
!       S0DEP    OPTICAL DEPTH FROM LAYER BOUNDARY TO SUN.
!       S0TRN    TRANSMITTED SOLAR IRRADIANCES [W CM-2 / CM-1]
!       UPF      LAYER BOUNDARY UPWARD THERMAL FLUX [W CM-2 / CM-1].
!       DNF      LAYER BOUNDARY DOWNWARD THERMAL FLUX [W CM-2 / CM-1].
!       UPFS     LAYER BOUNDARY UPWARD SOLAR FLUX [W CM-2 / CM-1].
!       DNFS     LAYER BOUNDARY DOWNWARD SOLAR FLUX [W CM-2 / CM-1].
      REAL CSSCAT,SLEGEN,CSZEN0,CSZEN,CSZENX,TCONT,TAUT,GTSCAT,COSBAR,  &
     &  BBGRND,BBNDRY,S0DEP,S0TRN,DEPRAT,UPF,DNF,UPFS,DNFS
      COMMON/MSRD/CSSCAT,SLEGEN(0:MAZ),                                 &
     &  CSZEN0(LAYDIM),CSZEN(LAYDIM),CSZENX(LAYDIM),TCONT(LAYDIM),      &
     &  TAUT(MXKSUB,LAYDIM),GTSCAT(0:MXCMU,1:LAYDIM),COSBAR(LAYDIM),    &
     &  BBGRND,BBNDRY(LAYDIM),S0DEP(MXKSUB,LAYTWO),S0TRN(MXKSUB,LAYTWO),&
     &  DEPRAT(MXKSUB,LAYDIM),UPF(MXKSUB,LAYDIM),DNF(MXKSUB,LAYDIM),    &
     &  UPFS(MXKSUB,LAYDIM),DNFS(MXKSUB,LAYDIM)

!     DECLARE LOCAL VARIABLES
      INTEGER LP1
      REAL RIDIF,DSTDIF,DSTRAT,PROD

!     COSINE OF THE SOLAR ZENITH AT UPPER LAYER BOUNDARY
      CSZEN0(L)=COS(ANGLE/DEG)

!     COSINE OF THE SOLAR ZENITH AVERAGED FOR LAYER.
      IF(L.GT.1)CSZEN(L-1)=.5*(CSZEN0(L-1)+CSZEN0(L))

!     COSINE OF THE SOLAR ZENITH EXITING THE LAYER ABOVE.
      IF(L.GE.IKMAX1)RETURN
      LP1=L+1
      RIDIF=(RFNDX(L)-RFNDX(LP1))/(1.+RFNDX(LP1))
      DSTDIF=(ZM(LP1)-ZM(L))/(REE+ZM(LP1))
      DSTRAT=1.-DSTDIF
      PROD=(1.+RIDIF)*DSTRAT
      CSZENX(L)=.5*(ABS(CSZEN0(L))+                                     &
     &  SQRT((CSZEN0(L)*PROD)**2+(1.+PROD)*(DSTDIF-RIDIF*DSTRAT)))
      RETURN
      END
