      SUBROUTINE SVSOLA(IPARM,IPH,IDAY,ISOURC,PARM1,PARM2,              &
     &  PARM3,PARM4,TIME,G,ANGLEM,IPRMSV,IPHSV,IDAYSV,                  &
     &  ISRCSV,PRM1SV,PRM2SV,PRM3SV,PRM4SV,TIMESV,GSV,ANGMSV)

!     SAVE THE CURRENT SOLAR PARAMETERS.
      INTEGER IPH,IPARM,IDAY,ISOURC,IPRMSV,IPHSV,IDAYSV,ISRCSV
      REAL PARM1,PARM2,PARM3,PARM4,TIME,G,ANGLEM,                       &
     &  PRM1SV,PRM2SV,PRM3SV,PRM4SV,TIMESV,GSV,ANGMSV
      IPRMSV=IPARM
      IPHSV=IPH
      IDAYSV=IDAY
      ISRCSV=ISOURC
      PRM1SV=PARM1
      PRM2SV=PARM2
      PRM3SV=PARM3
      PRM4SV=PARM4
      TIMESV=TIME
      GSV=G
      ANGMSV=ANGLEM
      RETURN
      END
