      FUNCTION TNRAIN(RR,V,TM,RADFLD)

!     COMMON/RCNSTN/
!       PI       THE CONSTANT PI
!       DEG      NUMBER OF DEGREES IN ONE RADIAN.
!       BIGNUM   MAXIMUM SINGLE PRECISION NUMBER.
!       BIGEXP   MAXIMUM EXPONENTIAL ARGUMENT WITHOUT OVERFLOW.
!       RRIGHT   SMALLEST SINGLE PRECISION REAL ADDED TO 1 EXCEEDS 1.
      REAL PI,DEG,BIGNUM,BIGEXP,RRIGHT
      COMMON/RCNSTN/PI,DEG,BIGNUM,BIGEXP,RRIGHT
!CC   CALCULATES TRANSMISSION DUE TO RAIN AS A FUNCTION OF
!CC   RR=RAIN RATE IN MM/HR
!CC   OR WITHIN 350CM-1 USES THE MICROWAVE TABLE ROUTINE TO
!CC   OBTAIN THE EXTINCTION DUE TO RAIN
!CC   RANGE=SLANT RANGE KM
!CC
!CC   ASSUMES A MARSHALL-PALMER RAIN DROP SIZE DISTRIBUTION
!CC   N(D)=NZERO*EXP(-A*D)
!CC   NZERO=8.E3 (MM-1)  (M-3)
!CC   A=41.*RR**(-0.21)
!CC   D=DROP DIAMETER (CM)
!CC
      REAL NZERO
      DATA NZERO /8000./
!CC
      A=41./RR**0.21
!CC
      IF(RR.LE.0)TNRAIN=1.
      IF(RR.LE.0)RETURN
!CC
      IF(V.GE.350.0) THEN
       TNRAIN=PI*NZERO/A**3
      ELSE
       TNRAIN=GMRAIN(V,TM,RR)
       TNRAIN = TNRAIN * RADFLD
      END IF
      RETURN
      END
