      SUBROUTINE CRDRIV(TP5_FLAG,TP5_FILE,TP5_LINENUMBER)

!     THIS ROUTINE IS THE DRIVER FOR CLOUD/RAIN MODELS 1 THROUGH 10.
      IMPLICIT NONE

!     ARGUMENTS:
!DRF    TP5_FLAG LOGICAL FLAG IF READING IN TP5 FILE
!DRF    TP5_FILE STRING CONTAINING TP5 FILE INFORMATION
!DRF    TP5_LINENUMBER (I/O) CURRENT LINENUMBER FOR TP5 READING
      INTEGER TP5_LINENUMBER
      LOGICAL TP5_FLAG
      CHARACTER TP5_FILE(1000)*110

!     LOCAL VARIABLES:
      DOUBLE PRECISION CTHICK
      REAL CWDCOL,CIPCOL

!     DETERMINE CLOUD/RAIN DENSITY PROFILES
      CALL CRPROF(CTHICK,CWDCOL,CIPCOL,TP5_FLAG,TP5_FILE,TP5_LINENUMBER)

!     MERGE OLD ATMOSPHERIC AND CLOUD/RAIN LAYER BOUNDARY DATA.
      CALL CRMERG

!     DETERMINE CLOUD/RAIN SPECTRAL DATA
      CALL CRSPEC(SNGL(CTHICK),CWDCOL,CIPCOL,TP5_FLAG,TP5_FILE,         &
     &            TP5_LINENUMBER)

!     RETURN TO MODTRAN DRIVER ROUTINE
      RETURN
      END
