      SUBROUTINE CRDRIV(M_CLOUD_LIQ,WVL_CLD,EXT_LIQ_CLD,SSA_LIQ_CLD,    &
     &                ASYM_LIQ_CLD,M_CLOUD_ICE,EXT_ICE_CLD,             &
     &                SSA_ICE_CLD,ASYM_ICE_CLD,NUM_LEVS,Z_CLD_VAL,      &
     &                LATITUDE_INPUT,LONGITUDE_INPUT)

      INTEGER NUM_LEVS
      REAL M_CLOUD_LIQ(NUM_LEVS-1)
      REAL M_CLOUD_ICE(NUM_LEVS-1)
      REAL WVL_CLD(24),EXT_LIQ_CLD(24)
      REAL SSA_LIQ_CLD(24),ASYM_LIQ_CLD(24)
      REAL EXT_ICE_CLD(24),SSA_ICE_CLD(24),ASYM_ICE_CLD(24)
      REAL Z_CLD_VAL(NUM_LEVS-1) !WAVELENGTHS FOR CLOUD OPT. PROPERTIES
      REAL LATITUDE_INPUT,LONGITUDE_INPUT

!     THIS ROUTINE IS THE DRIVER FOR CLOUD/RAIN MODELS 1 THROUGH 10.
      REAL CTHICK,CWDCOL,CIPCOL

!     DETERMINE CLOUD/RAIN DENSITY PROFILES
      CALL CRPROF(CTHICK,CWDCOL,CIPCOL,M_CLOUD_LIQ,M_CLOUD_ICE,NUM_LEVS,&
     &            Z_CLD_VAL,LATITUDE_INPUT,LONGITUDE_INPUT)

!      CALL CRPROF(CTHICK,CWDCOL,CIPCOL,M_CLOUD_LIQ,O_CLOUD_LIQ,         &
!     &            M_CLOUD_ICE,O_CLOUD_ICE,AC_WAVELEN,NUM_LEVS,          &
!     &            NUM_AC_WVL)

!     MERGE OLD ATMOSPHERIC AND CLOUD/RAIN LAYER BOUNDARY DATA.
      CALL CRMERG

!     DETERMINE CLOUD/RAIN SPECTRAL DATA
      CALL CRSPEC(CTHICK,CWDCOL,CIPCOL,WVL_CLD,EXT_LIQ_CLD,             &
     &            SSA_LIQ_CLD,ASYM_LIQ_CLD,EXT_ICE_CLD,                 &
     &            SSA_ICE_CLD,ASYM_ICE_CLD,NUM_LEVS,NUM_AC_WVL)

!     RETURN TO MODTRAN DRIVER ROUTINE
      RETURN
      END
