
!     LOGICAL SWITCH USED BY JMASS
!       LJMASS   LOGICAL SWITCH FOR JMASS IF TRUE
      LOGICAL LJMASS
      PARAMETER (LJMASS = .FALSE.)

      INTEGER FATAL, WARNING, SUCCESS
      PARAMETER (FATAL=2,WARNING=1,SUCCESS=0)

      INTEGER MAXERR
      PARAMETER(MAXERR=500)

      INTEGER OUTPUTCOUNT, ERRORCODE, LSTERR
      COMMON /ERRORDATA/ OUTPUTCOUNT, ERRORCODE, LSTERR

      CHARACTER*512 ERRORBUF
      COMMON /ERRORCHAR/ ERRORBUF(0:MAXERR)
