      REAL FUNCTION EXPINT(X1,X2,A)

!     EXPONENTIAL INTERPOLATION FOR POSITIVE ARGUMENTS
      REAL X1,X2,A
      IF(X1.GT.0. .AND. X2.GT.0.)THEN
          EXPINT=X1*(X2/X1)**A
      ELSE
          EXPINT=X1+(X2-X1)*A
      ENDIF
      RETURN
      END
