      SUBROUTINE O2INT(V1C,V1,DV,NPT,C,CARRAY,A,AARRAY,B,BARRAY)

!     INTERPOLATION FOR O2 PRESSURE INDUCED CONTINUUM, NECESSARY FOR
!     LOWTRAN7 FORMULATION (MODELED AFTER THE LOWTRAN UV-O3 BANDS)

      DIMENSION CARRAY(74),AARRAY(74),BARRAY(74)
      I=INT((V1C-V1)/DV+1.00001)
      IF(I.GE.1 .AND. I.LE.NPT)THEN
          C=CARRAY(I)
          A=AARRAY(I)
          B=BARRAY(I)
      ELSE
          C=0.
          A=0.
          B=0.
      ENDIF
      RETURN
      END
