      REAL FUNCTION O3HHT0(V)

!     COMMONS:
      INTEGER NC
      REAL V1C,DVC,O3HH0X
      COMMON/O3HH0/V1C,DVC,NC,O3HH0X(2687)

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      SAVE /O3HH0/
      EXTERNAL BO3HH0

!     FUNCTIONS:
      REAL O3INT
      O3HHT0=O3INT(V,V1C,DVC,NC,O3HH0X)
      RETURN
      END
