      REAL FUNCTION O3HHT2(V)

!     COMMONS:
      INTEGER NC
      REAL V1C,DVC,O3HH2X
      COMMON/O3HH2/V1C,DVC,NC,O3HH2X(2687)

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      SAVE /O3HH2/
      EXTERNAL BO3HH2

!     FUNCTIONS:
      REAL O3INT

!     INTERPOLATE TO DATA:
      O3HHT2=O3INT(V,V1C,DVC,NC,O3HH2X)
      RETURN
      END
