      SUBROUTINE RAIN(V,EXT,ABT,SCT,ASYMR)

!     PARAMETERS:
      INTEGER PHASE,DIST
      INCLUDE 'PARAMS.h'

!     COMMONS:
      INCLUDE 'BASE.h'

!     COMMON/RCNSTN/
!       PI       THE CONSTANT PI.
!       DEG      NUMBER OF DEGREES IN ONE RADIAN.
!       BIGNUM   MAXIMUM SINGLE PRECISION NUMBER.
!       BIGEXP   MAXIMUM EXPONENTIAL ARGUMENT WITHOUT OVERFLOW.
!       RRIGHT   SMALLEST SINGLE PRECISION REAL ADDED TO 1 EXCEEDS 1.
      REAL PI,DEG,BIGNUM,BIGEXP,RRIGHT
      COMMON/RCNSTN/PI,DEG,BIGNUM,BIGEXP,RRIGHT
      INTEGER IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA
      REAL VIS,WSS,WHH,RAINRT
      COMMON/CARD2/IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA,                 &
     &  VIS,WSS,WHH,RAINRT
      TMPRN=W(61)/W(3)
      VTEMP=1.438786*V
      IF(VTEMP.GE.TMPRN*BIGEXP)THEN
          RFD=V
      ELSE
          STORE=EXP(-VTEMP/TMPRN)
          RFD=V*(1.-STORE)/(1.+STORE)
      ENDIF
      RAINAV=(W(3)/W(62))**(1./.63)
      IF(V.LT.250.)THEN
          PHASE=1
          IF(ICLD.GT.11)PHASE=2
          DIST=1

!         CALL SCATTERING ROUTINE TO OBTAIN ASYMMETRY
!         FACTOR AND RATIO OF ABSORPTION TO EXTINCTION DUE
!         TO RAIN WITHIN RANGE OF 19 TO 231 GHZ.
!         EXTRAPOLATE ABOVE AND BELOW THAT FREQ RANGE
          CALL RNSCAT(V,RAINAV,TMPRN,PHASE,DIST,CSSA,ASYMR)
      ELSE
          CSSA=.5
          ASYMR=.85
      ENDIF
      RNEXPH=TNRAIN(RAINAV,V,TMPRN,RFD)*W(62)
      EXT=RNEXPH
      ABT=RNEXPH*CSSA
      SCT=RNEXPH*(1.-CSSA)
      RETURN
      END
