      REAL FUNCTION RANDOM()
      DOUBLE PRECISION DRND
      SAVE DRND
      DATA DRND/0.574914365D0/
      DRND=97301.D0*DRND
      DRND=DRND-DBLE(INT(DRND))
      RANDOM=REAL(DRND)
      RETURN
      END
