      SUBROUTINE RDNSM

      INCLUDE 'ERROR.h'

!     THIS SUBROUTINE READS MODEL 7 DATA WHEN IVSA EQ 1

!     COMMONS:
      INCLUDE 'IFIL.h'

!     /CARD1/
      INTEGER MODEL,ITYPE,IEMSCT,M1,M2,M3,IM,NOPRNT
      LOGICAL MODTRN
      COMMON/CARD1/MODEL,ITYPE,IEMSCT,M1,M2,M3,IM,NOPRNT,MODTRN
      COMMON /CARD1A/ M4,M5,M6,MDEF,IRD1,IRD2
      INTEGER JUNITP,JUNITT,JUNIT,JLOW
      REAL WMOL
      COMMON/CARD1B/JUNITP,JUNITT,JUNIT(13),WMOL(12),JLOW
      INTEGER IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA
      REAL VIS,WSS,WHH,RAINRT
      COMMON/CARD2/IHAZE,ISEASN,IVULCN,ICSTL,ICLD,IVSA,                 &
     &  VIS,WSS,WHH,RAINRT

!     /CNTRL/
!       IKMAX    NUMBER OF PATH SEGMENTS ALONG LINE-OF-SIGHT.
!       ML       NUMBER OF ATMOSPHERIC PROFILE LEVELS.
!       MLFLX    NUMBER OF LEVELS FOR WHICH FLUX VALUES ARE WRITTEN.
!       ISSGEO   LINE-OF-SIGHT FLAG (0 = SENSOR PATH, 1 = SOLAR PATHS).
!       IMULT    MULTIPLE SCATTERING FLAG
!                  (0=NONE, 1=AT SENSOR, -1=AT FINAL OR TANGENT POINT).
      INTEGER IKMAX,ML,MLFLX,ISSGEO,IMULT
      COMMON/CNTRL/IKMAX,ML,MLFLX,ISSGEO,IMULT
      COMMON/NSINP/ZM(40),P(40),T(40),WMDL(40,12)

!     FUNCTIONS:
!       JOU      TRANSLATE UNIT SPECIFIER CHARACTER INTO INTEGER LABEL.
      INTEGER JOU

!     DECLARE BLOCK DATA ROUTINES EXTERNAL:
      EXTERNAL DEVCBD
      CHARACTER*1 JCHAR
      DIMENSION  JCHAR(15)
      IF(ML. GT. 24) THEN
         WRITE(IPR,900) ML
900      FORMAT('  ML = ',I5,'  GT 24 ML RESET TO 24')
         ML = 24
      ENDIF
      JLOW = 1
      DO 200   K=1,ML
      DO 10 KM = 1,15
      JCHAR(KM) = ' '
      IF(KM. GT. 12) GO TO 10
      WMOL(KM) = 0.
10    CONTINUE
      IRD0 = 1
      IF(MODEL.GT.0 .AND. MODEL.LT.7)IRD0 = 0
      IF(IRD0.EQ.1 .AND. IVSA.EQ.1)IRD0 = 0

!        PARAMETERS - JCHAR = INPUT KEY (SEE BELOW)

!     ***  ROUTINE ALSO ACCEPTS VARIABLE UNITS ON PRESS AND TEMP

!          SEE INPUT KEY BELOW

!     FOR MOLECULAR SPECIES ONLY

!       JCHAR   JUNIT

!     " ",A      10    VOLUME MIXING RATIO (PPMV)
!         B      11    NUMBER DENSITY (CM-3)
!         C      12    MASS MIXING RATIO (GM(K)/KG(AIR))
!         D      13    MASS DENSITY (GM M-3)
!         E      14    PARTIAL PRESSURE (MB)
!         F      15    DEW POINT TEMP (TD IN T(K)) - H2O ONLY
!         G      16     "    "     "  (TD IN T(C)) - H2O ONLY
!         H      17    RELATIVE HUMIDITY (RH IN PERCENT) - H2O ONLY
!         I      18    AVAILABLE FOR USER DEFINITION
!        1-6    1-6    DEFAULT TO SPECIFIED MODEL ATMOSPHERE

!     ****************************************************************
!     ****************************************************************

!     ***** OTHER 'JCHAR' SPECIFICATIONS -

!       JCHAR   JUNIT

!      " ",A     10    PRESSURE IN (MB)
!          B     11       "     "  (ATM)
!          C     12       "     "  (TORR)
!         1-6   1-6    DEFAULT TO SPECIFIED MODEL ATMOSPHERE

!      " ",A     10    AMBIENT TEMPERATURE IN DEG(K)
!          B     11       "         "       "  " (C)
!          C     12       "         "       "  " (F)
!         1-6   1-6    DEFAULT TO SPECIFIED MODEL ATMOSPHERE

!     ***** DEFINITION OF "DEFAULT" CHOICES FOR PROFILE SELECTION *****

!      FOR THE USER WHO WISHES TO ENTER ONLY SELECTED ORIGINAL
!      VERTICAL PROFILES AND WANTS STANDARD ATMOSPHERE SPECIFICATIONS
!      FOR THE OTHERS, THE FOLLOWING OPTION IS AVAILABLE

!     *** JCHAR(P,T OR K) MUST = 1-6 (AS ABOVE)

!      FOR MOLECULES 8-35, ONLY US STD PROFILES ARE AVIALABLE
!      THEREFORE, WHEN  'JCHAR(K) = 1-5', JCHAR(K) WILL BE RESET TO 6

      IF(LJMASS) THEN
         CALL INITCARD( 'CARD2C1' )
      ELSE
         READ(IRD,80)ZM(K),P(K),T(K),WMOL(1),WMOL(2),WMOL(3),           &
     &    (JCHAR(KM),KM=1,15)
80       FORMAT ( F10.3,5E10.3,15A1)
         WRITE(IPR,81)ZM(K),P(K),T(K),WMOL(1),WMOL(2),WMOL(3),          &
     &    (JCHAR(KM),KM=1,15)
81       FORMAT ( F10.3,1P5E10.3,10X,15A1)
      ENDIF
      IF(ZM(K) .LE. 2.0)JLOW = K
      IF(IRD1 .EQ. 1) THEN
         IF(LJMASS) THEN
            CALL INITCARD( 'CARD2C2' )
         ELSE
            READ(IRD,83)(WMOL(KM),KM=4,12)
83          FORMAT(8E10.3)
            WRITE(IPR,84)(WMOL(KM),KM=4,12)
84          FORMAT(1P8E10.3)
         ENDIF
      ENDIF

!     AHAZE =  AEROSOL VISIBLE EXTINCTION COFF (KM-1)
!     AT A WAVELENGTH OF 0.55 MICROMETERS

!     EQLWCZ=LIQUID WATER CONTENT (PPMV) AT ALT Z
!            FOR AEROSOL, CLOUD OR FOG MODELS

!     RRATZ=RAIN RATE (MM/HR) AT ALT Z

!     IHA1 AEROSOL MODEL USED FOR SPECTRAL DEPENDENCE OF EXTINCTION

!     IVUL1 STRATOSPHERIC AEROSOL MODEL USED FOR SPECTRAL DEPENDENCE
!     OF EXT AT Z

!     ICLD1 CLOUD MODEL USED FOR SPECTRAL DEPENDENCE OF EXT AT Z

!     ONLY ONE OF IHA1,ICLD1  OR IVUL1 IS ALLOWED
!     IHA1 NE 0 OTHERS IGNORED
!     IHA1 EQ 0 AND ICLD1 NE 0 USE ICLD1

!     IF AHAZE AND EQLWCZ ARE BOTH ZERO
!        DEFAULT PROFILE ARE LOADED FROM IHA1,ICLD1,IVUL1
!     ISEA1 = AEROSOL SEASON CONTROL FOR ALTITUDE Z

      IF(IRD2 .EQ. 1) THEN
         IF(LJMASS) THEN
            CALL INITCARD( 'CARD2C3' )
         ELSE
            READ(IRD,82)    AHAZE,EQLWCZ,RRATZ,IHA1,ICLD1,IVUL1,ISEA1
            WRITE(IPR,82)    AHAZE,EQLWCZ,RRATZ,IHA1,ICLD1,IVUL1,ISEA1
82          FORMAT(10X,3F10.3,4I5)
         ENDIF
      ENDIF
      DO 12 KM=1,13
          JUNIT(KM)=JOU(JCHAR(KM+2),6)
   12 CONTINUE
      IF(M1.NE.0)THEN
          JUNITP=M1
          JUNITT=M1
      ELSE
          JUNITP=JOU(JCHAR(1),M1)
          JUNITT=JOU(JCHAR(2),M1)
      ENDIF
      CALL CHECKP(P(K),JUNITP)
      CALL CHECKT(T(K),JUNITT)
      CALL DEFALT(ZM(K),P(K),T(K))
      CALL CONVRT (P(K),T(K) )
      DO 20 KM = 1,12
20    WMDL(K,KM) = WMOL(KM)
200   CONTINUE
      RETURN
      END
